/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:8fc7e31b-ca2a-4d56-9668-190edf1797a7",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_yHAaqYBhL",
    "aws_user_pools_web_client_id": "1el7pt8bdd01nso8bshql3dftq",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": "6",
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "api",
            "endpoint": "https://uhhev8gu2d.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        }
    ],
    "aws_user_files_s3_bucket": "macrosaiad14aa54695f42bf9505b09aad5276176256f-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
